name: immunex
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  model_viewer_plus: ^1.9.3
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/human.glb
    - assets/heart.glb
    - assets/brain.glb
    - assets/lungs.glb
    - assets/liver.glb
    - assets/organism.glb
    - assets/icon/icon.png
